manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob-fork
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: urob-fork
      revision: mouse-3.2
      import: app/west.yml
  self:
    path: config
